### PR TITLE
Fix C++ Warnings

### LINKED ISSUE #317: C++ warnings when compiling Scaler
There are compiler warnings when compiling Scaler:

```
[ 12%] Building CXX object scaler/object_storage/CMakeFiles/object_storage_server_objs.dir/object_manager.cpp.o
[ 12%] Built target object_storage_server_objs
[ 14%] Building CXX object scaler/io/ymq/CMakeFiles/ymq_objs.dir/epoll_context.cpp.o
In file included from /home/amruth/citi_work/opengris-scaler/scaler/io/ymq/epoll_context.h:12,
                 from /home/amruth/citi_work/opengris-scaler/scaler/io/ymq/epoll_context.cpp:3:
/home/amruth/citi_work/opengris-scaler/scaler/io/ymq/timed_queue.h:62:7: warning: ‘scaler::ymq::TimedQueue’ has a field ‘scaler::ymq::TimedQueue::PriorityQueue scaler::ymq::TimedQueue::pq’ whose type has internal linkage [-Wsubobject-linkage]
   62 | class TimedQueue {
      |       ^~~~~~~~~~

```

### PR DESCRIPTION
**Pull request by magniloquency**
Closes #317

### CODE REVIEW

File: scaler/io/ymq/timed_queue.h [hunk 1]
```diff
@@ -19,6 +19,16 @@
 namespace scaler {
 namespace ymq {
 
+template <typename T>
+struct TimestamplessCompare {
+    bool operator()(const T& x, const T& y) const { return std::get<0>(x) < std::get<0>(y); }
```
Comment (gxuu) [inline scaler/io/ymq/timed_queue.h]: `constexpr`,

File: scaler/io/ymq/timed_queue.h [hunk 2]
```diff
@@ -19,6 +19,16 @@
 namespace scaler {
 namespace ymq {
 
+template <typename T>
```
Comment (gxuu) [inline scaler/io/ymq/timed_queue.h]: If you write `TimestamplessCompare` then do not use `typename T`. Just make it take normal variable or qualify it with concept.

**Comment by gxuu** [comment]
I think it is better to just silent the warning with respect to this warning.

File: scaler/io/ymq/timed_queue.h [hunk 3]
```diff
@@ -19,6 +19,16 @@
...
+struct TimestamplessCompare {
+    bool operator()(const T& x, const T& y) const { return std::get<0>(x) < std::get<0>(y); }
+};
+
+using Callback            = Configuration::TimedQueueCallback;
```
[the remark this answers is not in the document]
Comment (magniloquency) [reply scaler/io/ymq/timed_queue.h]: Ok, how can I fix it? I can't put the `using` inside the struct/class, because then the type has internal linkage

**Comment by magniloquency** [comment]
> I think it is better to just silent the warning with respect to this warning.

@sharpener6, thoughts?

File: scaler/io/ymq/timed_queue.h (hunk 2 above)
Comment (rafa-be) [reply scaler/io/ymq/timed_queue.h]: @magniloquency What he says is that it does not make sense to make it a template, just use the plain `Timestamp` type:

```c++
bool operator()(const Timestamp& x, const Timestamp& y)
```

File: scaler/io/ymq/timed_queue.h (hunk 1 above)
Comment (magniloquency) [reply scaler/io/ymq/timed_queue.h]: done

**Comment by magniloquency** [comment]
> Still have warning?

The warnings are gone now, @sharpener6

**Review by sharpener6 — APPROVED** [review]
